services:
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000" # python -m http.server 8000, for index.html
    stdin_open: true
    tty: true
